# -*- coding: utf-8 -*-
"""DM-Task1&2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLagEqamqAXaGskJUHLBk_WchrSr4fYo

# Task 1

Q1
"""

import numpy as np
import pandas as pd
import zipfile

def load_data(path='kmeans_data.zip'):
  with zipfile.ZipFile(path, 'r') as z:
    with z.open('data.csv') as df:
      X_df = pd.read_csv(df, header=None)
    X = X_df.values.astype(np.float64)

    with z.open('label.csv') as df:
      y_df = pd.read_csv(df, header=None)
    y = y_df.values.ravel().astype(int)
  return X,y

X,y = load_data()

X.shape

y.shape

np.unique(y)

print(X)

def euc_dist(a,b):
  diff = a-b
  sqdiff = diff ** 2
  sum_sq = np.sum(sqdiff, axis=1)
  dist = np.sqrt(sum_sq)
  return dist

def cosine_dist(a,b):
  a_norm =np.linalg.norm(a)
  b_norm =np.linalg.norm(b)
  res =np.dot(a,b)/(a_norm * b_norm)
  res =np.clip(res,-1,1)
  return 1-res

def jaccard_dist(a,b):
  a_sum=np.sum(np.minimum(a,b),axis=1)
  m_sum=np.sum(np.maximum(a,b),axis=1)
  res = a_sum/m_sum
  return 1-res

def kmeans(X,K,fun,i=250):
    n,D = X.shape
    centroids = X[np.random.choice(n,K,replace=False)]
    for q in range(i):
        distances = np.zeros((X.shape[0], K))
        for k in range(K):
            distances[:, k] = fun(X, centroids[k])
        labels = np.argmin(distances, axis=1)
        new_centroids = np.zeros_like(centroids)
        for k in range(K):
            points = X[labels == k]
            if len(points) > 0:
                new_centroids[k] = points.mean(axis=0)
            else:
                new_centroids[k] = centroids[k]

        centroids = new_centroids
    sse = 0
    for k in range(K):
        cluster_points = X[labels == k]
        if len(cluster_points) > 0:
            sse += np.sum(fun(cluster_points, centroids[k]))
    return labels, centroids, sse
K = len(np.unique(y))

np.random.seed(42)
a1,a2,sse_euc =kmeans(X,K,euc_dist)
a1,a2,sse_cos =kmeans(X,K,cosine_dist)
a1,a2,sse_jac =kmeans(X,K,jaccard_dist)

"""Compare the SSEs of Euclidean-K-means, Cosine-K-means, Jarcard-K-means. Which method is better?"""

print("SSE Euclidean:",sse_euc)
print("SSE Cosine:",sse_cos)
print("SSE Jaccard: ",sse_jac)

ans = min(sse_euc,sse_cos,sse_jac)
if ans ==sse_euc:
    print("\nEuclidean kmeans is better")
elif ans == sse_cos:
    print("\nCosine kmeans is better")
else:
    print("\nJaccard kmeans is better")

"""Q2"""

def compute_accuracy(X, y_true, K,func, i=100):
    N, D = X.shape
    centr = X[np.random.choice(N, K, replace=False)]

    for q in range(i):
        distbw = np.zeros((X.shape[0], K))
        for k in range(K):
            distbw[:, k] = func(X,centr[k])
        labels = np.argmin(distbw,axis=1)

        new_c = np.zeros_like(centr)
        for k in range(K):
            pc=X[labels==k]
            if len(pc)>0:
                new_c[k] =pc.mean(axis=0)
            else:
                new_c[k] = centr[k]

        centr=new_c
    cluster_labels = np.zeros(K, dtype=int)

    for k in range(K):
        mask = (labels == k)
        if np.sum(mask) > 0:
            cluster_labels[k] = np.bincount(y_true[mask]).argmax()
    pred = cluster_labels[labels]
    acc = np.mean(pred == y_true)
    return acc



K = len(np.unique(y))
np.random.seed(42)
acc_euc = compute_accuracy(X,y,K,euc_dist)
acc_cos = compute_accuracy(X,y,K,cosine_dist)
acc_jac = compute_accuracy(X,y,K,jaccard_dist)

print("Kmeans : ")
print("accuracy Euclidean:",acc_euc)
print("accuracy Cosine:",acc_cos)
print("accuracy Jaccard: ",acc_jac)

ans = max(acc_euc,acc_cos,acc_jac)
if ans ==acc_euc:
    print("\nEuclidean kmeans is better")
elif ans ==acc_cos:
    print("\nCosine kmeans is better")
else:
    print("\nJaccard kmeans is better")

"""Q3"""

import numpy as np
import time

def kmeans_convergence(X, K, func, max_iter=500, no_change=0.0001):
    N, D = X.shape
    centroids = X[np.random.choice(N, K, replace=False)]
    prev_sse = np.inf
    count = 0
    start = time.time()
    for _ in range(max_iter):
        count += 1
        distances = np.zeros((N, K))
        for k in range(K):
            distances[:, k] = func(X, centroids[k])
        labels = np.argmin(distances, axis=1)
        new_centroids = np.zeros_like(centroids)
        for k in range(K):
            pts = X[labels == k]
            if len(pts) > 0:
                new_centroids[k] = pts.mean(axis=0)
            else:
                new_centroids[k] = centroids[k]
        sse = 0
        for k in range(K):
            pts = X[labels == k]
            if len(pts) > 0:
                sse += np.sum(func(pts, new_centroids[k]))
        if np.all(np.abs(new_centroids - centroids) < no_change):
            break
        if sse > prev_sse:
            break
        centroids = new_centroids
        prev_sse = sse
    elapsed = time.time()-start
    return count, elapsed

K = len(np.unique(y))
np.random.seed(42)
iters_euc, time_euc = kmeans_convergence(X,K,euc_dist)
iters_cos, time_cos = kmeans_convergence(X,K,cosine_dist)
iters_jac, time_jac = kmeans_convergence(X,K,jaccard_dist)

print(f"Euclidean K means: {iters_euc} iterations, {time_euc} sec")
print(f"Cosine K means: {iters_cos} iterations, {time_cos} sec")
print(f"Jaccard K means: {iters_jac} iterations, {time_jac} sec")

print("\n*******Comparison *******")
if iters_euc >= iters_cos and iters_euc >= iters_jac:
    print("Euclidean K means requires the most iterations")
elif iters_cos >= iters_euc and iters_cos >= iters_jac:
    print("Cosine K means requires the most iterations")
else:
    print("Jaccard K means requires the most iterations")

print("\n***** Time Comparison ****")
if time_euc >= time_cos and time_euc >= time_jac:
    print("Euclidean K means takes the most time to converge")
elif time_cos >= time_euc and time_cos >= time_jac:
    print("Cosine K means takes the most time to converge")
else:
    print("Jaccard K means takes the most time to converge")

"""Q4"""

def kmeans_sse_term1(X,K,func,no_change=0.0005):
    N, D = X.shape
    centroids = X[np.random.choice(N, K, replace=False)]
    for _ in range(100):
        distances = np.zeros((X.shape[0], K))
        for k in range(K):
            distances[:, k] = func(X, centroids[k])

        labels = np.argmin(distances, axis=1)

        new_centroids = np.zeros_like(centroids)
        for k in range(K):
            points = X[labels == k]
            if len(points) > 0:
                new_centroids[k] = points.mean(axis=0)
            else:
                new_centroids[k] = centroids[k]
        if np.all(np.abs(new_centroids - centroids) < no_change):
            break
        centroids = new_centroids
    sse = 0
    for k in range(K):
        cluster_points = X[labels == k]
        if len(cluster_points) > 0:
            sse += np.sum(func(cluster_points, centroids[k]))
    return sse

def kmeans_sse_term2(X,K,func):
    N,D=X.shape
    centroids = X[np.random.choice(N, K, replace=False)]
    prev_sse = np.inf
    for _ in range(100):
        distances = np.zeros((X.shape[0], K))
        for k in range(K):
            distances[:, k] = func(X, centroids[k])

        labels = np.argmin(distances, axis=1)

        new_centroids = np.zeros_like(centroids)
        for k in range(K):
            points = X[labels == k]
            if len(points) > 0:
                new_centroids[k] = points.mean(axis=0)
            else:
                new_centroids[k] = centroids[k]

        sse = 0
        for k in range(K):
            cluster_points = X[labels == k]
            if len(cluster_points) > 0:
                sse += np.sum(func(cluster_points, new_centroids[k]))
        if sse > prev_sse:
            break
        prev_sse = sse
        centroids = new_centroids
    return prev_sse

def kmeans_sse_term3(X,K,func,i=150):
    N,D= X.shape
    centroids = X[np.random.choice(N, K, replace=False)]

    for i in range(i):
        distances = np.zeros((N, K))
        for k in range(K):
            distances[:, k] = func(X, centroids[k])
        labels = np.argmin(distances, axis=1)
        new_centroids = np.zeros_like(centroids)
        for k in range(K):
            points = X[labels == k]
            if len(points) > 0:
                new_centroids[k] = points.mean(axis=0)
            else:
                new_centroids[k] = centroids[k]
        centroids = new_centroids
    sse = 0
    for k in range(K):
        cluster_points = X[labels == k]
        if len(cluster_points) > 0:
            sse += np.sum(func(cluster_points, centroids[k]))

    return sse

K = len(np.unique(y))
np.random.seed(42)
sse_euc1 = kmeans_sse_term1(X,K,euc_dist)
sse_cos1 = kmeans_sse_term1(X,K,cosine_dist)
sse_jac1 = kmeans_sse_term1(X,K,jaccard_dist)
sse_euc2 = kmeans_sse_term2(X,K,euc_dist)
sse_cos2 = kmeans_sse_term2(X,K,cosine_dist)
sse_jac2 = kmeans_sse_term2(X,K,jaccard_dist)
sse_euc3 = kmeans_sse_term3(X,K,euc_dist)
sse_cos3 = kmeans_sse_term3(X,K,cosine_dist)
sse_jac3 = kmeans_sse_term3(X,K,jaccard_dist)

print("process 1: No change in centroid:")
print("Euclidean: ",sse_euc1)
print("Cosine: ",sse_cos1)
print("Jaccard: ",sse_jac1)

print("\nprocess 2: sse increases in next iteration:")
print("Euclidean: ",sse_euc2)
print("Cosine: ",sse_cos2)
print("Jaccard: ",sse_jac2)

print("\nprocess 3: after max iterations: ")
print("Euclidean: ",sse_euc3)
print("Cosine: ",sse_cos3)
print("Jaccard: ",sse_jac3)

"""Q 5.

*   jaccard for k means has given best results with the lowes sse compared to others.
*   cosine and jacarrd also perform better in the accuracies for the label.
*   Cosine is better than jaccard in accuracy.


*   Cosine takes less iteration and time to converge.
*   ecludean is not perfroming well compared to other two methods.
"""



"""# Task 2"""

!pip install numpy==1.26.4
!pip install scikit-surprise

import matplotlib.pyplot as plt
import seaborn as sns
from surprise import Dataset, Reader
from surprise import SVD, KNNBasic
from surprise.model_selection import cross_validate, GridSearchCV
from surprise.accuracy import rmse, mae
sns.set_style('whitegrid')

import numpy as np
import pandas as pd

df1=pd.read_csv('ratings_small.csv')

df1.head()

reader = Reader(line_format='user item rating timestamp', sep=',', rating_scale=(1,5))

data = Dataset.load_from_df(df1[['userId','movieId','rating']], reader)

"""#c. Compute the average MAE and RMSE of the Probabilistic Matrix Factorization (PMF), User based Collaborative Filtering, Item based Collaborative Filtering,under the 5-folds cross-validation (10 points)

**the average MAE and RMSE of the Probabilistic Matrix Factorization (PMF)**
"""

pmf=SVD()
pmf_res=cross_validate(pmf,data,measures=['RMSE','MAE'],cv=5,verbose=False)

print(pmf_res)

print("pmf average RMSE:",pmf_res['test_rmse'].mean())
print("pmf average MAE:",pmf_res['test_mae'].mean())

"""**User based Collaborative Filtering**"""

user_based_cf=KNNBasic(sim_options={'name':'msd','user_based':True})
user_based_res=cross_validate(user_based_cf,data,measures=['RMSE','MAE'],cv=5,verbose=False)

print("user based cf average RMSE:", user_based_res['test_rmse'].mean())
print("user based cf average MAE :", user_based_res['test_mae'].mean())



"""**Item based Collaborative Filtering**"""

item_based_cf =KNNBasic(sim_options={'name':'msd','user_based':False})
item_based_res =cross_validate(item_based_cf,data, measures=['RMSE','MAE'],cv=5,verbose=False)

print("item based cf average RMSE:",item_based_res['test_rmse'].mean())
print("item based cf average MAE:",item_based_res['test_mae'].mean())

"""##d. Compare the average (mean) performances of User-based collaborative filtering, item-based collaborative filtering, PMF with respect to RMSE and MAE. Which ML model is the best in the movie rating data? (10 points)"""

print("pmf")
print(pmf_res['test_rmse'].mean())
print(pmf_res['test_mae'].mean())
print("\nuser based cf")
print(user_based_res['test_rmse'].mean())
print(user_based_res['test_mae'].mean())
print("\nitem based cf")
print(item_based_res['test_rmse'].mean())
print(item_based_res['test_mae'].mean())

"""Which ML model is the best in the movie rating data?

Pmf has the lowest rmse and mae error as compared to other two methods which means that it is a good option for the prediction model .also we can see that user based cf is having highest rmse and mae which shows that it has poor similarity so it is not a good option for our ML model.
"""



"""##e. Examine how the cosine, MSD (Mean Squared Difference), and Pearson similarities impact the performances of User based Collaborative Filtering and Item based Collaborative Filtering. Plot your results. Is the impact of the three metrics on User based Collaborative Filtering consistent with the impact of the three metrics on Item based Collaborative Filtering? (10 points)"""

user_e_rmse = []
item_e_rmse = []
user_e_mae = []
item_e_mae = []

user_based1 =KNNBasic(sim_options={'name':'cosine','user_based':True}, k=50)
item_based1 =KNNBasic(sim_options={'name':'cosine','user_based':False}, k=50)
u_res1 =cross_validate(user_based1,data,measures=['RMSE','MAE'],cv=5,verbose=False)
i_res1 =cross_validate(item_based1,data,measures=['RMSE','MAE'],cv=5,verbose=False)
user_e_rmse+=[np.mean(u_res1['test_rmse'])]
item_e_rmse+=[np.mean(i_res1['test_rmse'])]
user_e_mae+=[np.mean(u_res1['test_mae'])]
item_e_mae+=[np.mean(i_res1['test_mae'])]

print("user cosine rmse:",np.mean(u_res1['test_rmse']))
print("item cosine rmse:",np.mean(i_res1['test_rmse']))
print("user cosine mae:",np.mean(u_res1['test_mae']))
print("item cosine mae:",np.mean(i_res1['test_mae']))

user_based2 =KNNBasic(sim_options={'name':'msd','user_based':True},k=50)
item_based2 =KNNBasic(sim_options={'name':'msd','user_based':False}, k=50)
u_res2 =cross_validate(user_based2,data,measures=['RMSE','MAE'],cv=5,verbose=False)
i_res2 =cross_validate(item_based2,data,measures=['RMSE','MAE'],cv=5,verbose=False)
user_e_rmse+=[np.mean(u_res2['test_rmse'])]
item_e_rmse +=[np.mean(i_res2['test_rmse'])]
user_e_mae+=[np.mean(u_res2['test_mae'])]
item_e_mae+=[np.mean(i_res2['test_mae'])]

print("user msd rmse:",np.mean(u_res2['test_rmse']))
print("user msd mae:",np.mean(u_res2['test_mae']))
print("item msd rmse:",np.mean(i_res2['test_rmse']))
print("item msd mae:",np.mean(i_res2['test_mae']))

user_based3 =KNNBasic(sim_options={'name':'pearson','user_based':True},k=50)
item_based3 =KNNBasic(sim_options={'name':'pearson','user_based':False},k=50)
u_res3 =cross_validate(user_based3,data, measures=['RMSE','MAE'], cv=5,verbose=False)
i_res3 =cross_validate(item_based3,data, measures=['RMSE','MAE'],cv=5,verbose=False)
user_e_rmse+=[np.mean(u_res3['test_rmse'])]
item_e_rmse+=[np.mean(i_res3['test_rmse'])]
user_e_mae+=[np.mean(u_res3['test_mae'])]
item_e_mae+=[np.mean(i_res3['test_mae'])]

print("user pearson rmse:",np.mean(u_res3['test_rmse']))
print("user pearson mae:",np.mean(u_res3['test_mae']))
print("item pearson rmse:",np.mean(i_res3['test_rmse']))
print("item pearson mae:",np.mean(i_res3['test_mae']))

print(user_e_rmse)
print(item_e_rmse)
print(user_e_mae)
print(item_e_mae)

import matplotlib.pyplot as plt
x = np.arange(3)
labels = ['Pearson','Cosine','MSD']
width = 0.25
fig, ax = plt.subplots(ncols=2, figsize=(12,5))
ax[0].bar(x - width/2,user_e_rmse,width,label='User cf',color='skyblue')
ax[0].bar(x + width/2,item_e_rmse,width,label='Item cf',color='pink')
ax[0].set_ylabel('rmse')
ax[0].set_xticks(x)
ax[0].set_xticklabels(labels)
ax[0].set_ylim(0,1)
ax[0].set_title('comparision of Similarity Metric on RMSE')
ax[1].bar(x - width/2,user_e_mae,width,label='User cf',color='skyblue')
ax[1].bar(x + width/2,item_e_mae,width,label='Item cf',color='pink')
ax[1].set_ylabel('mae')
ax[1].set_ylim(0,1)
ax[1].set_xticks(x)
ax[1].set_xticklabels(labels)
ax[1].set_title('comparision of Similarity Metric on MAE')
plt.tight_layout()
plt.show()

"""In RMSE, Cosine is performing better than other two for users and items both.
In MAE also cosine is performing better than other two methods for both users and items . Cosine is significantly better for item in both the cases, for users cosine shows better performance by a small margin.
"""



"""##f. Examine how the number of neighbors impacts the performances of User based Collaborative Filtering and Item based Collaborative Filtering? Plot your results. (10 points)"""

n=[5,10,15,20,30,40,50]
user_f_rmse=[]
item_f_rmse=[]
user_f_mae=[]
item_f_mae=[]

for i in n:
  user_based_f =KNNBasic(sim_options={'name':'msd','user_based':True},k=i)
  item_based_f =KNNBasic(sim_options={'name':'msd','user_based':False},k=i)
  u_res_f =cross_validate(user_based_f,data,measures=['RMSE','MAE'],cv=5,verbose=False)
  i_res_f =cross_validate(item_based_f,data,measures=['RMSE','MAE'],cv=5,verbose=False)
  user_f_rmse+=[np.mean(u_res_f['test_rmse'])]
  item_f_rmse+=[np.mean(i_res_f['test_rmse'])]
  user_f_mae+=[np.mean(u_res_f['test_mae'])]
  item_f_mae+=[np.mean(i_res_f['test_mae'])]

print("user rmse: ",user_f_rmse)
print("item rmse: ",item_f_rmse)
print("user mae: ",user_f_mae)
print("item mae: ",item_f_mae)

plt.figure(figsize=(8,5))
plt.plot(n, user_f_rmse, marker='o', label='user rmse CF')
plt.plot(n, item_f_rmse, marker='s', label='item rmse CF')
plt.plot(n, user_f_mae, marker='o', label='user mae CF')
plt.plot(n, item_f_mae, marker='s', label='item mae CF')
plt.xlabel('Number of Neighbors (k)')
plt.ylabel('Average RMSE')
plt.title('Effect of Number of Neighbors on RMSE')
plt.legend()
plt.xticks(n)
plt.grid(True)
plt.show()

"""As the no of neighours (n) increases item based cf improves a lot with smaller n then it gets almost constant improvement with increasing n .

Another thing i noticed is that user based cf gets a little worse with n after a sudden improvement in the initial n values which may be due to noise from different neighour users.

g
"""

best_k_user = n[np.argmin(user_f_rmse)]
best_rmse_user = min(user_f_rmse)

best_k_item = n[np.argmin(item_f_rmse)]
best_rmse_item = min(item_f_rmse)

print(f"best n for user based cf is : {best_k_user}, and RMSE for the same is : {best_rmse_user:.4f}")
print(f"best n for user based cf is : {best_k_item}, and RMSE for the same is : {best_rmse_item:.4f}")

"""Is the best K of User based collaborative filtering the same with the best K of Item based collaborative filtering?

No, the K value is not the same for both , for user cf it gets best at 15 for my n samples while for item cf it gets best near 50 which was my last n sample.
"""

